services:
  backend:
    build:
      context: ./xeghepBE
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG
      LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER: TRACE
      LOGGING_FILE_PATH: /app/logs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ${DATA_ROOT:-../nghiaphat-data}/backend/logs:/app/logs
    restart: unless-stopped

  frontend:
    build:
      context: ./xeghepFE
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ${DATA_ROOT:-../nghiaphat-data}/db/data:/var/lib/postgresql/data
      - ${DATA_ROOT:-../nghiaphat-data}/db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  app-network:
    driver: bridge