version: '3.9'

services:
  backend:
    build:
      context: ./xeghepBE
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      TZ: Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://db:5432/postgres}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-vusuu4xcrJZJ13U}
      LOGGING_FILE_PATH: /app/logs
      SERVER_PORT: 8080
      JAVA_TOOL_OPTIONS: -Xmx3g -Xms1g
    networks:
      - app-network
    volumes:
      - backend_logs:/app/logs
      - ticket_images:/app/data/ticket-images
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.5"
          memory: 3.5G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./xeghepFE
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge

volumes:
  backend_logs:
    driver: local
  ticket_images:
    driver: local
